site: Index Jekyll Theme

url: https://cnoss.github.io
baseurl: 

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "images/small"
    values:
      image: true


markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  
sass:
  style: compressed

baseurl: "/benz"

## plugins:
#  - jekyll-paginate
#  - jekyll-sitemap

  